
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 03 20:23:31 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 14;
  public static final int READ = 6;
  public static final int IDENT = 30;
  public static final int PLUS = 10;
  public static final int RBRACE = 24;
  public static final int RPAREN = 22;
  public static final int EQUAL = 17;
  public static final int SEMI = 19;
  public static final int RETURN = 7;
  public static final int LBRACKET = 25;
  public static final int LBRACE = 23;
  public static final int LPAREN = 21;
  public static final int RBRACKET = 26;
  public static final int STRING = 31;
  public static final int INC = 15;
  public static final int COMMA = 20;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int COMMENT = 27;
  public static final int PROG = 2;
  public static final int DEC = 16;
  public static final int MINUS = 11;
  public static final int DOT = 18;
  public static final int CONST = 4;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int ENUM = 3;
  public static final int NEW = 9;
  public static final int BOOL = 28;
  public static final int MUL = 12;
  public static final int VOID = 8;
}

