
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 04 16:07:44 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 13;
  public static final int READ = 6;
  public static final int IDENT = 29;
  public static final int PLUS = 9;
  public static final int RBRACE = 23;
  public static final int RPAREN = 21;
  public static final int EQUAL = 16;
  public static final int SEMI = 18;
  public static final int RETURN = 7;
  public static final int LBRACKET = 24;
  public static final int LBRACE = 22;
  public static final int LPAREN = 20;
  public static final int RBRACKET = 25;
  public static final int STRING = 28;
  public static final int INC = 14;
  public static final int COMMA = 19;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int COMMENT = 26;
  public static final int PROG = 2;
  public static final int DEC = 15;
  public static final int MINUS = 10;
  public static final int DOT = 17;
  public static final int CONST = 4;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int ENUM = 3;
  public static final int NEW = 8;
  public static final int BOOL = 27;
  public static final int MUL = 11;
}

